# Generated by Django 4.1.1 on 2023-03-28 09:32

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('customerID', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('customerName', models.CharField(default='New User', max_length=50)),
                ('customerEmail', models.EmailField(blank=True, max_length=254)),
                ('customerAddress', models.CharField(blank=True, max_length=200)),
                ('customerMobile', models.CharField(blank=True, max_length=10)),
                ('customerImage', models.ImageField(blank=True, upload_to='')),
                ('customerAccountCreationDate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
